"""Markdown report renderer for PR comments / job summaries.

The output is plain GitHub-flavored Markdown, no external deps. It's
intentionally compact: header, by-severity table, top-N findings table,
by-scanner breakdown. Anything more verbose belongs in the SARIF output.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from typing import Iterable

from .finding import Finding
from .severity import Severity


SEVERITY_ORDER = (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.NONE)
SEVERITY_BADGE = {
    Severity.CRITICAL: "🔴 CRITICAL",
    Severity.HIGH: "🟠 HIGH",
    Severity.MEDIUM: "🟡 MEDIUM",
    Severity.LOW: "🔵 LOW",
    Severity.NONE: "⚪ NONE",
}


def render_markdown(findings: list[Finding], *, top_n: int = 10) -> str:
    if not findings:
        return _empty_report()

    parts: list[str] = []
    parts.append("# 🔐 Security scan summary")
    parts.append("")
    parts.append(_subtitle(findings))
    parts.append("")
    parts.append(_severity_table(findings))
    parts.append("")
    parts.append(_top_findings_table(findings, top_n))
    parts.append("")
    parts.append(_by_scanner_section(findings))
    parts.append("")
    parts.append(_footer())
    return "\n".join(parts)


def _subtitle(findings: list[Finding]) -> str:
    total = len(findings)
    cross = sum(1 for f in findings if f.confidence >= 2)
    return (
        f"**{total}** unique findings after merging across "
        f"{len(_all_scanners(findings))} scanners. "
        f"**{cross}** corroborated by 2+ scanners (severity bumped one level)."
    )


def _severity_table(findings: list[Finding]) -> str:
    counts = Counter(f.severity for f in findings)
    rows = [f"| {SEVERITY_BADGE[s]} | {counts[s]} |" for s in SEVERITY_ORDER if counts[s]]
    if not rows:
        return ""
    head = "| Severity | Count |\n| --- | ---: |"
    return "## By severity\n\n" + head + "\n" + "\n".join(rows)


def _top_findings_table(findings: list[Finding], n: int) -> str:
    head = (
        "## Top findings\n\n"
        "| Severity | Confidence | Where | Rule | Sources | Message |\n"
        "| --- | :---: | --- | --- | --- | --- |"
    )
    rows = []
    for f in findings[:n]:
        loc = f"`{_md_escape(f.location.file)}`"
        if f.location.line:
            loc += f":{f.location.line}"
        msg = _truncate(_md_escape(f.message), 100)
        sources = ", ".join(f.sources)
        rule = _md_escape(f.rule_id)
        rows.append(
            f"| {SEVERITY_BADGE[f.severity]} | "
            f"{f.confidence}× | {loc} | `{rule}` | {sources} | {msg} |"
        )
    return head + "\n" + "\n".join(rows)


def _by_scanner_section(findings: list[Finding]) -> str:
    counts = Counter()
    for f in findings:
        for s in f.sources:
            counts[s] += 1
    rows = [f"| `{name}` | {count} |" for name, count in sorted(counts.items())]
    return "## By scanner\n\n| Scanner | Findings |\n| --- | ---: |\n" + "\n".join(rows)


def _all_scanners(findings: Iterable[Finding]) -> set[str]:
    seen: set[str] = set()
    for f in findings:
        seen.update(f.sources)
    return seen


def _footer() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"<sub>Generated by [sarif-merge](https://github.com/AaronGrillot98/sarif-merge) · {ts}</sub>"


def _empty_report() -> str:
    return (
        "# 🔐 Security scan summary\n\n"
        "✅ No findings across any scanner. Nothing to merge.\n\n"
        + _footer()
    )


def _md_escape(s: str) -> str:
    """Escape pipe and newline characters that would break Markdown tables."""
    if not s:
        return ""
    return s.replace("|", "\\|").replace("\n", " ").strip()


def _truncate(s: str, n: int) -> str:
    if len(s) <= n:
        return s
    return s[: n - 1].rstrip() + "…"
