"""Markdown renderer + SARIF emitter."""

import json

from sarif_merge.dedupe import dedupe
from sarif_merge.finding import Finding, Location
from sarif_merge.output import to_sarif
from sarif_merge.render import render_markdown
from sarif_merge.sarif import load_sarif, parse_findings
from sarif_merge.score import apply_consensus
from sarif_merge.severity import Severity


# ---------- markdown rendering ----------

def test_empty_findings_renders_clean_message():
    md = render_markdown([])
    assert "✅ No findings" in md
    assert "Generated by [sarif-merge]" in md


def test_renders_severity_table_and_top_findings(all_scanner_files):
    raw = []
    for p in all_scanner_files:
        raw.extend(parse_findings(load_sarif(p)))
    scored = apply_consensus(dedupe(raw))
    md = render_markdown(scored)

    assert "Security scan summary" in md
    assert "By severity" in md
    assert "Top findings" in md
    assert "By scanner" in md
    # Cross-scanner finding shows the bumped CRITICAL.
    assert "CRITICAL" in md
    # Scanner names lowercased.
    assert "`bandit`" in md
    assert "`trivy`" in md


def test_pipe_in_message_is_escaped():
    f = Finding(
        rule_id="R", rule_name="r",
        message="bad | character will break tables",
        severity=Severity.HIGH,
        location=Location(file="a.py", line=1),
        sources=("x",), base_severity=Severity.HIGH,
    )
    md = render_markdown([f])
    # Escaped form should appear, raw form should not (in row context).
    assert "bad \\| character" in md


def test_long_message_is_truncated():
    f = Finding(
        rule_id="R", rule_name="r",
        message="x" * 500,
        severity=Severity.HIGH,
        location=Location(file="a.py", line=1),
        sources=("x",), base_severity=Severity.HIGH,
    )
    md = render_markdown([f])
    # Truncation appends a single-character ellipsis.
    assert "…" in md


def test_subtitle_counts_cross_scanner_findings():
    cross = Finding(
        rule_id="R", rule_name="r", message="m", severity=Severity.HIGH,
        location=Location(file="a.py", line=1),
        sources=("x", "y"), confidence=2, base_severity=Severity.MEDIUM,
    )
    solo = Finding(
        rule_id="R2", rule_name="r2", message="m", severity=Severity.LOW,
        location=Location(file="b.py", line=1),
        sources=("x",), confidence=1, base_severity=Severity.LOW,
    )
    md = render_markdown([cross, solo])
    assert "**2** unique findings" in md
    assert "**1** corroborated by 2+ scanners" in md


# ---------- SARIF output ----------

def test_emit_sarif_is_well_formed(all_scanner_files):
    raw = []
    for p in all_scanner_files:
        raw.extend(parse_findings(load_sarif(p)))
    scored = apply_consensus(dedupe(raw))
    doc = to_sarif(scored)

    assert doc["$schema"].startswith("https://")
    assert doc["version"] == "2.1.0"
    assert isinstance(doc["runs"], list) and len(doc["runs"]) == 1
    run = doc["runs"][0]
    assert run["tool"]["driver"]["name"] == "sarif-merge"
    assert isinstance(run["tool"]["driver"]["rules"], list)
    assert len(run["results"]) == 5  # matches dedupe count above


def test_emitted_sarif_round_trips_through_our_parser(all_scanner_files, tmp_path):
    """The SARIF we emit must be re-parseable by our own parser without loss."""
    raw = []
    for p in all_scanner_files:
        raw.extend(parse_findings(load_sarif(p)))
    scored = apply_consensus(dedupe(raw))
    doc = to_sarif(scored)
    out_path = tmp_path / "merged.sarif"
    out_path.write_text(json.dumps(doc), encoding="utf-8")

    re_parsed = list(parse_findings(load_sarif(out_path)))
    assert len(re_parsed) == len(scored)


def test_emitted_results_carry_sources_and_confidence(all_scanner_files):
    raw = []
    for p in all_scanner_files:
        raw.extend(parse_findings(load_sarif(p)))
    scored = apply_consensus(dedupe(raw))
    doc = to_sarif(scored)

    # The shell-injection finding should have 3 sources in its emitted properties.
    shell_results = [
        r for r in doc["runs"][0]["results"]
        if r["locations"][0]["physicalLocation"]["artifactLocation"]["uri"] == "src/talonedge/cli.py"
    ]
    assert len(shell_results) == 1
    props = shell_results[0]["properties"]
    assert sorted(props["sources"]) == ["bandit", "semgrep", "trivy"]
    assert props["confidence"] == 3
    assert props["consensus_severity"] == "CRITICAL"
    assert props["base_severity"] == "HIGH"
